AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation templates to create S3 buckets. **WARNING** You will
  be billed for data stored in AWS S3 buckets if you create a stack from this template.
Parameters:
  QSDeploymentSuffix:
    Type: String
    Default: qs
    ConstraintDescription: Deployment suffix can include numbers, lowercase letters
      and should have the maximum length of 7 characters.
    Description: You can deploy this Quick Start multiple times in the same region
      if you provide a different suffix that is added to resource names to make them
      unique per each deployment. Use this parameter to support deployment of production
      and test environments in the same region in the same AWS account.
    AllowedPattern: '[a-z0-9]+'
    MinLength: 1
    MaxLength: 12
  EnableS3LifecycleRules:
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'yes'
    Description: Enable S3 lifecycle rules
    Type: String
  GlacierTransitionPeriodInDays:
    Default: 365
    Description: Number of days after which data is transitioned to Glacier.
    Type: Number
  IATransitionPeriodInDays:
    Default: 90
    Description: Number of days after which data is transitioned to IA.
    Type: Number
Mappings:
  Constants:
    Buckets:
      AsTableDataPath: as_structure_sync/
      AthenaResultBucketNamePrefix: athena-idc-query-results
      CuratedDataNamePrefix: dl-curated-datasets
      CuratedDatasetsDataPath: data/
      CuratedDatasetsNumericDataPath: data/numeric/
      CuratedDatasetsTextDataPath: data/text/
      PublishedDataNamePrefix: dl-published-data
      SubmissionsNamePrefix: dl-submissions
    S3LifecycleStatus:
      'yes': Enabled
      'no': Disabled
Resources:
  CuratedDataBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !FindInMap
            - Constants
            - Buckets
            - CuratedDataNamePrefix
          - !Ref 'AWS::AccountId'
          - !Ref 'AWS::Region'
          - !Ref 'QSDeploymentSuffix'
      LifecycleConfiguration:
        Rules:
          - Id: MoveToIAThenGlacier
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: !Ref 'IATransitionPeriodInDays'
              - StorageClass: GLACIER
                TransitionInDays: !Ref 'GlacierTransitionPeriodInDays'
            Prefix: !FindInMap
              - Constants
              - Buckets
              - CuratedDatasetsDataPath
            Status: !FindInMap
              - Constants
              - S3LifecycleStatus
              - !Ref 'EnableS3LifecycleRules'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    Type: AWS::S3::Bucket
  PublishedDataBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !FindInMap
            - Constants
            - Buckets
            - PublishedDataNamePrefix
          - !Ref 'AWS::AccountId'
          - !Ref 'AWS::Region'
          - !Ref 'QSDeploymentSuffix'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    Type: AWS::S3::Bucket
  SubmissionsBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !FindInMap
            - Constants
            - Buckets
            - SubmissionsNamePrefix
          - !Ref 'AWS::AccountId'
          - !Ref 'AWS::Region'
          - !Ref 'QSDeploymentSuffix'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    Type: AWS::S3::Bucket
Outputs:
  CuratedDataBucketARN:
    Value: !GetAtt 'CuratedDataBucket.Arn'
    Description: Bucket for Curated Data - ARN
  CuratedDataBucketName:
    Value: !Ref 'CuratedDataBucket'
    Description: Bucket for Curated Data - name
  SubmissionsBucketName:
    Value: !Ref 'SubmissionsBucket'
    Description: Bucket name for submissions
  PublishedDataBucketName:
    Value: !Ref 'PublishedDataBucket'
    Description: Bucket name for Published Data
